version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=your_password
    ports:
      - '8080:80'
    depends_on:
      - db
